config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", passwords: 'passwords', confirmations: 'confirmations' }
  default_url_options :host => "www.paytonbray.com"
  
  resources :users
  resources :skills
  
  get 'pages/home'
  get 'pages/events'
  get 'pages/talent'
  get 'pages/leadership'
  get 'pages/mailcheck'
  post 'users/add_skill'
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/skill.rb
class Skill < ApplicationRecord
    has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_attached_file :avatar, styles: { original: {convert_options: '-auto-orient'}, medium: "300x300>", thumb: "100x100>" }, 
  default_url: "social.png" 
  #,source_file_options: {all: '-auto-orient;'}
  
  
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
  
  validates :name, presence: true 

  has_and_belongs_to_many :skills

  def self.search(search)
    
    find_by_sql("SELECT DISTINCT users.* FROM users
    INNER JOIN skills_users ON users.id = skills_users.user_id 
    INNER JOIN skills ON skills_users.skill_id = skills.id
    WHERE users.name @@ '%#{search}%' OR users.description @@ '%#{search}%' OR users.email @@ '%#{search}%' 
    OR users.title @@ '%#{search}%' OR users.organization @@ '%#{search}%' OR skills.name @@ '%#{search}%'") 

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
  before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :title, :organization, :description, :display_phone, :area_code, :prefix, :line_number, :mentor, :avatar ])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email, :password, :password_confirmation])
      
    end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    edit_user_registration_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def events
  end

  def talent
    @users = User.paginate(:page => params[:page], :per_page => 10)
  end

  def leadership 
  end

  def mailcheck
  end

end

app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController
  protected
  def after_sending_reset_password_instructions_path_for(resource_name)
    pages_mailcheck_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def edit
    @skills = @user.skills.order(:created_at)
    @skill = Skill.new
    super
  end
  
    protected
    
    def after_sign_up_path_for(users)
      pages_mailcheck_path
    end

    def after_update_path_for(resource)
      edit_user_registration_path
    end

    def update_resource(resource, params)
      resource.update_without_password(params)
    end

end
 

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

    
    def create 
      @skill = Skill.find(params[:select_tag])
      
      @user = current_user
      @user.skills << @skill
      
      #@skill.save!
      
      respond_to do |format|
        format.html { redirect_to edit_user_registration_path }
        format.js
      end
  
    end

    

    def add_skill_params
        params.require(:skill).permit(:name)
    end

    def show
      @skill = Skill.find(params[:id])
    end
    
    def destroy
      @skill = Skill.find(params[:id])

      current_user.skills.destroy(params[:id])

      respond_to do |format|
        format.html { redirect_to edit_user_registration_path }
        format.js
      end
    end


    def add_skill
      @skill = Skill.find(params[:id])
      
      ActiveRecord::Base.connection.execute("INSERT INTO skills_users ('skill_id', 'user_id') VALUES ('%#{@skill.id}%', '%#{current_user.id}%')")
      
      @skill.save!
      
      respond_to do |format|
        format.html { redirect_to edit_user_registration_path }
        format.js
      end

    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @skills = @user.skills
  end

  def update 
    @user = User.find(current_user.id)

    if @user.update_attributes(update_user_params)
      render "pages/home"
    else
      render 'edit'
    end
  end

  def update_user_params
    params.require(:user).permit(:name, :description, :area_code, :prefix, :line_number)
  end

  def index 
    if params[:search].blank?
      @users = User.order(:name) 
    else
      @users = User.search(params[:search])
      params.delete :search
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navPartial.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1 class="text-left"><%= link_to "SOE", root_path %></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="has-dropdown">
        <a href="#">Profile</a>
        <ul class="dropdown">
          <% if user_signed_in?%>
            <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <%else%>

            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <%end%>
        </ul>
      </li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li><%= link_to 'Events', pages_events_path %></li>
      <li><%= link_to 'Talent', users_path %></li>
      <li><%#= link_to 'Leadership', pages_leadership_path %></li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= stylesheet_link_tag 'application', media: "only screen and (min-width: 401px)" %>
    

    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Open+Sans" rel="stylesheet"> 

    <title><%= content_for?(:title) ? yield(:title) : "SOE" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render "layouts/navPartial"%>
    <%= yield %>    
    <%= javascript_include_tag "application" %>

  </body>

</html>

app/views/pages/events.html.erb
<div class="row">
  <div class="small-12">
    <h1>Events</h1>

    <!-- start feedwind code --> <script type="text/javascript" src="https://feed.mikle.com/js/fw-loader.js" data-fw-param="57972/"></script> <!-- end feedwind code --> 
</div>
</div>

app/views/pages/home.html.erb
<div class="row">
		<div class="small-12 small-centered columns" id="homehead">
			<h1 class="show-for-medium-up">Society of entrepreneurs</h1>
			<h1 class="show-for-small">SOE</h1>
		</div>
</div>



<div class="row">
	<ul class="small-block-grid-1 medium-block-grid-3">
		<li><%= image_tag  "soe1.jpg" %></li>
		<li class="show-for-medium-up"><%= image_tag  "soe6.jpg" %></li>
		<li class="show-for-medium-up"><%= image_tag  "soe7.jpg" %></li>
	</ul>
</div>


<div class="row">
	<div class = "small-12 medium-8 small-centered columns">
		<h1>Network. Create. Experience.</h1>
		
		<p class="text-center">SOE is a student organization that highlights the entrepreneurial mindset. We serve as the connection to entrepreneurs in Athens and Atlanta. SOE supports student startups both on and off campus. </p>

	</div>
</div>

<div class="row">
	<ul class="small-block-grid-1 medium-block-grid-2">
		<li class="show-for-medium-up"><%= image_tag  "soe8.jpg" %></li>
		<li><%= image_tag  "soe3.jpg" %></li>
	</ul>
</div>
	


<div class="row">
	<div class="small-12 medium-8 small-centered columns">
			<h1>Who are we for?</h1>
			<p class="text-center">Anyone who aspires to operate their own organization, business, or non-profit. <br>No business? No problem. SOE welcomes anyone who wishes to support the startup community. </p>
			<p class="text-center"></p>
	</div>
</div>

<div class="row">
	<ul class="small-block-grid-1 medium-block-grid-3">
		<li class="show-for-medium-up"><%= image_tag  "soe4.jpg" %></li>
		<li><%= image_tag  "soe2.jpg" %></li>
		<li class="show-for-medium-up"><%= image_tag  "soe5.jpg" %></li>
	</ul>
</div>
	

<div class='row'>
	<div class="small-12 medium-8 small-centered columns">
		<h1 class="text-center">Our vision</h1>
		<p class="text-center">UGA's premier student organization encompassing hundreds 
			spanning across campus passionate about creative thinking, curiosity,
		  and growth on an individual & community level. Ultimately, the 
			organization where students learn to bring their ideas to life, 
			surrounded by the right people to help along the way.</p>
		</div>
</div>
	
<div class="row">
	<h1>Need to Reach Us?
	</h1>
	<p class="text-center">shoot us an email at <a href="mailto:ugasoe1@gmail.com" style="color:#3cb0fd">soe@uga.edu</a> <br>
	or <br>
	Follow us on social media!</p>			
</div>

<div class="row" style="padding-bottom: 5px;">	
		<div class="small-6 small-centered columns text-center medialink"><a href="https://www.instagram.com/soeuga/" id="submit-button"><i class="fa fa-instagram" aria-hidden="true">Instagram</i></a></div>
</div>

<div class="row" style="padding-bottom: 5px;">	
		<div class="small-6 small-centered columns text-center medialink"><a href="https://www.facebook.com/soeuga/" id="submit-button"><i class="fa fa-facebook-square" aria-hidden="true">Facebook</i></a></div>
</div>

<div class="row" style="padding-bottom: 5px;">	
		<div class="small-6 small-centered columns text-center medialink"><a href="#" id="submit-button"><i class="fa fa-snapchat-ghost" aria-hidden="true">soeuga</i></a></div>
</div>

<div class="row">
	<div class="small-12 columns" style="height: 150px;">
	</div>
</div>

<footer>
	<div class="row fullwidth">
		<div class="small-12 medium-6 small-centered text-center columns">
			<p class="text-center" style="font-size: 12px;">
				Developed and managed by Young Spark Consulting LLC
			</p>
		</div>
	</div>
</footer>


<%#= <div class="row full-length" id="leaders"> 
	<div class="small-12 columns">
		<h2>MEET THE LEADERS OF SOE: </h2>
		<br>

		<div class="flexslider">
		  <ul class="slides">
		    <li>
		      <img src="slide1.jpg" />
		      <h3><a href="blaiseprofile">BLAISE McCOMB</a></h3>
		      <div class="text">Blaise strives to bring people together in an effort to create a strong startup ecosystem in Athens, GA. He interned for Umano and is involved in Pi Sigma Epsilon business fraternity.
		  	</div>
		    </li>
		    <li>
		      <img src="slide2.jpg" />
		    </li>
		    <li>
		      <img src="slide3.jpg" />
		    </li>
		    <li>
		      <img src="slide4.jpg" />
		    </li>
		  </ul>
		</div>

	</div>
</div>

%>


<%#=<div id="contact">
	<div class="main">
	<h1>CONTACT FORM HERE:</h1>
	<p>Name</p>
	<p>Email </p>
	<p>Comments </p>
	<p>Thank yoou for submitting your suggestion </p>
	</div>
</div>
%>

app/views/pages/leadership.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1 class="small-centered">Leadership</h1>
  </div>
</div>

<div class="row"

app/views/pages/mailcheck.html.erb
<div class="row">
  <div class="small-12 small-centered columns" style="height: 115px;">
  </div>
</div>
  

<div class="row">
  <div class="row">
    <div class="small-12 small-centered columns">
      <h1>Your email has been sent</h1><br>
    </div>
  </div>


  <div class="row">
    <div class="small-12 small-centered columns">
      <h1><small>Check your inbox</small></h1>
    </div>
  </div>
</div>

app/views/pages/talent.html.erb
<div class="main">
<h1>Talent</h1>

<%= will_paginate @users %></div>

app/views/skills/_addSkillForm.html.erb
  <%= form_for @skill, :url => { :action => "create", :controller => "skills"} do |f|%>

      <%= f.label "Skill Name" %>
      <%= f.text_field (:name) %>

      <%= f.submit ("Add this skill")%>
      
  <%end%>

app/views/skills/_skill.html.erb
<li class="skill-item" id = "skill_item_<%=skill.id%>">

    <p id="skill-p" class="text-center skill-p"><%= skill.name %>    <%= link_to "X", skill, method: :delete, id: "remove-link", remote: true%></p>

    <%= link_to "X", skill, method: :delete, remote: true %>
</li>

app/views/skills/_skills.html.erb
  <% @skills = @user.skills%>
  <% @skills.each do |c| %>
    <li></li>
    <div id="skillBox"><%= c.name %></div>
  <% end %>

app/views/skills/add_skill.js.erb
$('#skillsList').append("<%= j render @skill %>");

app/views/skills/create.js.erb
$('#skillsList').append("<%= j render @skill %>");

app/views/skills/destroy.js.erb
$("#skill_item_<%= @skill.id%>").remove();

app/views/users/add_skill.js.erb
$('#skillList').append("<%= j render @skill %>")

app/views/users/index.html.erb
<div class="row">
    <div class="small-12 medium-7 small-centered columns">
            <%= form_tag users_path, method: :get, id: "search-form" do %>
                <%= label_tag :q, "Find your team..." %>
                <%= text_field :search, params[:search], id: "search-field", placeholder: 'Skills, positions held, orgs., etc.' %>
                <%= submit_tag "Search", id: "submit-button" %>
            <% end %>
    </div>
</div>


<div class="row">
    
        <ul class="small-block-grid-1 medium-block-grid-3">
            <% if @users.empty? %>
                <div class="small-12" id="noUsersMatch"><h1 class="text-centered">We couldn't seem to find anyone</h1></div>
            <% else %>
                <%@users.each do |c|%>
                    <li class="search-result">
                        
                        <div class="row">

                            <%= link_to user_path(c.id) do %>
                                <div class="small-1 small-centered columns" id="indeximagecontainer">
                                    <%= image_tag c.avatar.url, id: "profile-thumb" %>
                                </div>
                            <%end%>

                        </div>

                        <div class="row">
                            <h2><%=c.name%> </h2>
                        </div>

                        <div class="row">
                            <h2><small style="font-size: 13px;"> <%=c.email %> </small></h2>
                        </div>
                        
                        <div class="show-for-medium-up row">
                            <div class="discription"><p class="text-center" style="font-size: 12px; color: black; margin: 0px; padding: 10px;"><%= c.description %></p></div>
                        </div>
                    
                    </li>   
                <%end%>
            <%end%>
        </ul>

</div>

app/views/users/show.html.erb
<div class="row spacer-top">
	<div class="small-8 small-centered columns">
		<ul class="small-block-grid-1 medium-block-grid-2">
			<li>
				<div class="show-for-small small-1 small-centered columns" id="indeximagecontainer"><%= image_tag  @user.avatar.url, id: "profile-thumb"%></div>
				<div class="show-for-medium-up small-1 small-centered columns" id="showimagecontainer"><%= image_tag  @user.avatar.url, id: "profile-thumb"%></div>
			</li>
			<li>
				<h2 class="text-center">
					<%=@user.name%> <br>
					<small>
						<% if @user.display_phone && @user.area_code? && @user.prefix? && @user.line_number? %>
							(<%= @user.area_code %>) <%= @user.prefix %> - <%= @user.line_number %>
							<br>
						<% end %>

						
						<%=@user.email %> <br>
						<% if @user.title? && @user.organization? %>
						<hr>
							<strong><%=@user.title %>:</strong>
							<%=@user.organization%>
						<% end %>
					</small>
					<hr class="show-for-small">
				</h2>
			</li>
		</ul>
	</div>
</div>

<div class="row">
	<div class="small-12 medium-8 small-centered columns">
		<p class="text-center" style="font-size: 16px; margin:0;">
			<%= @user.description %>				
		</p>
	</div>
	<hr class="show-for-small">
</div>


<div class="row">
	<div class="small-12 medium-8 small-centered columns">
		
		<h1 class="small-12 small-centered columns">skills</h1>
		
		<ul class="small-block-grid-3 medium-block-grid-6">
			<% @skills.each do |c| %>
				<li>
					<p id="skill-p" class="text-center"><%= c.name%></p>
				</li>
			<%end%>
		</ul>
	</div>
</div>